spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: "dci"
    password: "qwer1234"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
  jackson:
    serialization:
      wrap-root-value: false

server:
  port: 5000
  error:
    include-message: always