spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: "dci"
    password: "qwer1234"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
  jackson:
    serialization:
      wrap-root-value: false

server:
  error:
    include-message: always


TestConfig:
  postBookParams:
    title: title
    subtitle: subtitle
    isbn13: isbn13
    price: 42.42
    image: http://www.image.org
    url: http://www.url.org

